"""auto-vote

Revision ID: b979d1951510
Revises: 9935899c8aed
Create Date: 2022-10-03 21:23:14.619112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b979d1951510'
down_revision = '9935899c8aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('users', 'video_time',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'-'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'video_time',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'-'::character varying"))
    op.drop_table('votes')
    # ### end Alembic commands ###
